### ISSUE TITLE
Import fails with file does not exist

### ISSUE THREAD

**Issue by MisinformedDNA** [jasonmarcher/PowerTab#101]
I successfully installed PowerTab, but when I went to import it, I get errors:

> D:\Repos\corefxlab> import-module PowerTab
> WARNING: Configuration File does not exist: 'System.Collections.Hashtable'
> Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
> At C:\Users\50587\Documents\WindowsPowerShell\Modules\PowerTab\1.0.0\TabExpansionLib.ps1:1226
> char:39
> + ...     $DatabasePath = Join-Path (Split-Path $ConfigurationPath) "TabExp ...
> +                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.Po
>    werShell.Commands.JoinPathCommand
> 
> 
> Update .NET type list in tab completion database from currently loaded types?
> Loading .NET types.
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

I also added the import to `profile.ps1`, but the error still appears every time a new PowerShell host opens.

**Comment by MisinformedDNA** [comment]
How would I run `New-TabExpansionConfig` if the module isn't imported yet?

**Comment by perplexityjeff** [comment]
Just import the module and run the setup. Then run the export command.

**Comment by MisinformedDNA** [comment]
That's the whole point. I can't import the module because it errors out.

**Comment by perplexityjeff** [comment]
I had the same errors. You can still continue with the setup. Just ignore it as it is an error for the path missing. Continue the setup and then run the export command.

**Comment by jasonmarcher** [comment]
This isn't a blocked error, but I will get it fixed.  The module needs to recognized when it is loading from a clean slate.

**Comment by bradrn** [comment]
I'm running into this same problem. It seems to be a problem with the `New-TabExpansionConfig` cmdlet:
```
> New-TabExpansionConfig
Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\PowerTab\1.0.0\TabExpansionLib.ps1:1226 char:39
+ ...     $DatabasePath = Join-Path (Split-Path $ConfigurationPath) "TabExp ...
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
```

**Comment by bradrn** [comment]
I've been investigating this issue a bit and the problem seems to be this bit in `PowerTab.psm1` around line 96:
```powershell
    if ($ConfigurationPath) {
        $script:ConfigurationPathParam = $ConfigurationPath
    } elseif ($PrivateData = (Parse-Manifest).PrivateData) {
        $script:ConfigurationPathParam = $PrivateData
#       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  This line is the problem!
    } elseif (Test-Path (Join-Path (Split-Path $Profile) $ConfigFileName)) {
        $script:ConfigurationPathParam = (Join-Path (Split-Path $Profile) $ConfigFileName)
    } elseif (Test-Path (Join-Path $PSScriptRoot $ConfigFileName)) {
        $script:ConfigurationPathParam = (Join-Path $PSScriptRoot $ConfigFileName)
    }
```
It seems that `(Parse-Manifest).PrivateData` is a `System.Collections.Hashtable`, so when it gets converted to a string, the configuration path ends up with the value `"System.Collections.Hashtable"` - which obviously isn't a correct path. For a temporary workaround, you can copy the line `$script:ConfigurationPathParam = (Join-Path (Split-Path $Profile) $ConfigFileName)` (which works on my system) and paste it back at the end of the `if` block so that it overwrites $script:ConfigurationPathParam` with a correct path.
